services:
  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./kanbanize_front_end:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 100
      WATCHPACK_POLLING: "true"
    command: sh -c "npm install && npx next dev -H 0.0.0.0 -p 3000"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: 'True'
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/.pgpass:/tmp/.pgpass:ro
    entrypoint: >
      /bin/sh -c "
        cp /tmp/.pgpass /var/lib/pgadmin/.pgpass &&
        chown pgadmin:root /var/lib/pgadmin/.pgpass &&
        chmod 600 /var/lib/pgadmin/.pgpass &&
        /entrypoint.sh
      "

  nodeapp:
    image: node:20
    container_name: backend
    working_dir: /usr/src/app
    volumes:
      - ./kanbanize_back_end:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && node app.js"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - PGHOST=postgres


volumes:
  postgres_data:
